[build]
  base = "/"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "16"

[context.production]
  command = "cd client && npm install && npm run build"
